#pragma once
/*  main.hpp  – top-level application glue
    ───────────────────────────────────── */

#include <Arduino.h>

/* umbrella headers generated by your folder structure */
#include "include/_include.hpp"
#include "core/_core.hpp"
#include "ctrl/_ctrl.hpp"
#include "devices/_devices.hpp"
#include "utils/_utils.hpp"

/* ─── Application entry points (called from .ino) ─── */
void mainSetup();
void mainLoop();

/* ─── Helpers implemented in main.cpp ─────────────── */
void  initButtons();
void  updateButtons();
bool  isSystemOn();
bool  wasModeTogglePressed();

void  initPump();
void  stopPump();

void  initDisplay();
void  showStatus(const SystemState& s, bool pageEdge = false);

/* (startFlowMeasurement, readFlow, etc. are declared in
   their respective device headers; no need to repeat.) */
